/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //mySidebar: [{type: 'autogenerated', dirName: '.'}],

  mySidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        'intro',
        'installation',
        'validation-quickstart',
        'asynchronous-validation'
      ]
    },
    {
      type: 'category',
      label: 'Error Messages',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'error-messages', // Generate sidebar slice from docs/tutorials/easy
        },
      ]
    },
    {
      type: 'category',
      label: 'Validation Rules',
      collapsible: true,
      collapsed: false,
      items: [
        'available-validation-rules',
        'nested-and-wildcard-rules',
        'validating-passwords',
        'custom-validation-rules'
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsible: true,
      collapsed: false,
      className: 'examples-c',
      items: [
        {
          type: 'category',
          label: 'Vue',
          items: [
            {
              type: 'autogenerated',
              dirName: 'vue',
            }
          ]
        },
        {
          type: 'category',
          label: 'Angular',
          items: [
            {
              type: 'autogenerated',
              dirName: 'angular'
            }
          ],
        },
        {
          type: 'category',
          label: 'React',
          items: [
            {
              type: 'autogenerated',
              dirName: 'react'
            }
          ],
        }
      ]
    }
  ],
   
};

module.exports = sidebars;
